CREATE DATABASE QLDETAI_SV
GO
USE QLDETAI_SV
GO

CREATE TABLE SINHVIEN(
 MASV CHAR(6) NOT NULL,
 TENSV NVARCHAR(30) NOT NULL,
 SODT VARCHAR(10),
 LOP CHAR(6) NOT NULL,
 DIACHI NVARCHAR(50) NOT NULL,
 CONSTRAINT pk_SINHVIEN PRIMARY KEY(MASV)
 )
 GO

 CREATE TABLE DETAI(
 MADT CHAR(6) NOT NULL,
 TENDT NVARCHAR(50)  NOT NULL
 CONSTRAINT pk_DETAI PRIMARY KEY(MADT)
 )
 GO 

CREATE TABLE SINHVIEN_DETAI(
 MASV CHAR(6) NOT NULL,
 MADT CHAR(6) NOT NULL,
 NGAYBAOCAO DATETIME,
 CONSTRAINT pk_SINHVIEN_DETAI PRIMARY KEY(MASV, MADT),

 CONSTRAINT fk_Sinhvien_SINHVIEN_DETAI FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
 CONSTRAINT fk_detai_SINHVIEN_DETAI FOREIGN KEY(MADT) REFERENCES DETAI(MADT),
 )

INSERT INTO SINHVIEN(MASV,TENSV,SODT,LOP,DIACHI) VALUES('SV0001',N'Nguyễn Văn A', '0909029530','DTH04','Bình Chánh')
INSERT INTO SINHVIEN(MASV,TENSV,SODT,LOP,DIACHI) VALUES('SV0002',N'Nguyễn Văn B', '0909029531','DTH04','Bình Chánh')

INSERT INTO DETAI(MADT,TENDT) VALUES('DT0001',N'Đồ Án Cơ Sở')
INSERT INTO DETAI(MADT,TENDT) VALUES('DT0002',N'Đồ Án Tốt Nghiệp')


INSERT INTO SINHVIEN_DETAI(MASV,MADT) VALUES('SV0001',N'DT0001')
INSERT INTO SINHVIEN_DETAI(MASV,MADT) VALUES('SV0001',N'DT0002')

INSERT INTO SINHVIEN_DETAI(MASV,MADT) VALUES('SV0002',N'DT0001')
INSERT INTO SINHVIEN_DETAI(MASV,MADT) VALUES('SV0002',N'DT0002')
SELECT * FROM SINHVIEN_DETAI
--Thêm Mới Column
ALTER TABLE SINHVIEN_DETAI ADD GHICHU NVARCHAR(100) NOT NULL 
GO
-- Add Khóa Chính
ALTER TABLE SINHVIEN_DETAI ADD CONSTRAINT pk_SINHVIEN_DETAI PRIMARY KEY(MASV,MADT) 
GO
--Add Khóa Ngoại
ALTER TABLE SINHVIEN_DETAI ADD CONSTRAINT fk_SINHVIEN_SIINHVIEN_DETAI FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV) 
GO
ALTER TABLE SINHVIEN_DETAI ADD CONSTRAINT fk_DETAI_SINHVIEN_DETAI FOREIGN KEY(MADT) REFERENCES DETAI(MADT) 
SELECT MASV, TENSV  FROM SINHVIEN 
WHERE MASV IN( 'SV0001' ,'SV0002' ,'SV0003')
ORDER BY MASV ASC

---INNER JOIN
SELECT sv.MASV, sv.TENSV , sv_dt.MADT  FROM SINHVIEN sv
INNER JOIN SINHVIEN_DETAI sv_dt
ON sv.MASV = sv_dt.MASV 

--GROUP BY
SELECT sv.MASV, sv.TENSV   FROM SINHVIEN sv
INNER JOIN SINHVIEN_DETAI sv_dt
ON sv.MASV = sv_dt.MASV 
GROUP BY sv.MASV, sv.TENSV 

--LEFT JOIN
SELECT sv.MASV, sv.TENSV , sv_dt.MADT  FROM SINHVIEN sv
LEFT JOIN SINHVIEN_DETAI sv_dt
ON sv.MASV = sv_dt.MASV 

---RIGHT JOIN
SELECT sv.MASV, sv.TENSV , sv_dt.MADT,sv_dt.MASV    FROM SINHVIEN sv
RIGHT JOIN SINHVIEN_DETAI sv_dt
ON sv.MASV = sv_dt.MASV 
--- UNION 

SELECT MASV, TENSV  FROM SINHVIEN 
WHERE MASV IN( 'SV0001' ,'SV0002' ,'SV0003')
UNION
SELECT MASV, TENSV  FROM SINHVIEN 
WHERE MASV IN( 'SV0001' ,'SV0004' )
--- UNION 

SELECT MASV, TENSV  FROM SINHVIEN 
WHERE MASV IN( 'SV0001' ,'SV0002' ,'SV0003')
UNION
SELECT MASV, TENSV  FROM SINHVIEN 
WHERE MASV IN( 'SV0001' ,'SV0004' )
